apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-ingressgateway-certs
  namespace: istio-system
spec:
  commonName: istio-ingressgateway.istio-system.svc
  # Use ipAddresses if your LoadBalancer issues an IP
  ipAddresses:
  - 20.54.120.63
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: istio-ingressgateway-certs